### ISSUE TITLE
Bei Passwordabfrage soll der Text nicht editierbar sein

### ISSUE THREAD

**Issue by markstein** [JustPlainText/front#2]

**Comment by mihapek** [comment]
strange, on my system its not editable since the popup window is modal

**Comment by mihapek** [comment]
так у тебя можно писать в текст в то время, пока открыт попап или ты имеешь в виду после закрытия окошка не вводя пароль?

**Comment by markstein** [comment]
можно изменять текст с помощью таба. вечером покажу.

Am 02.05.2017 9:28 vorm. schrieb "mihapek" <notifications@github.com>:

**Comment by mihapek** [comment]
fixed
